version: '3.8'
services:
  mysql:
    image: mysql:5.5
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    networks:
      - testDB
        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9.7
    container_name: phpmyadmin
    volumes:
      - ./config.inc.php:/etc/phpmyadmin/config.inc.php
    ports:
      - 8080:80
    networks:
      - testDB

networks:
  testDB:
    driver: bridge
